### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by benjohnde** [Liftric/cognito-idp#28]
I suggest a potential rename of the project. The library itself gets more and more mature. We are using it in production right now. Still the name `Auth` is a bit too generic and not random enough to be some sort of artsy & fancy term.

I would use this issue to brainstorm about potential names as subject for a rename of this library. We don't have to rename the project and we are not under pressure. Hence, feel free to drop some suggestions and we will later this or next month either execute that change or silently but determinately remove that thought of our brains.

- Kognito
- CAuth
- Authnito

**Comment by Ingwersaft** [comment]
The official client SDK is called `cognitoidentityprovider`, so maybe `cognito-multiplatform-idp`

**Comment by gaebel** [comment]
> cognito-multiplatform-idp

I do also tend get more verbose instead of using a "fictional or combined" name (I like short names though).

**Comment by benjohnde** [comment]
More suggestion to not be fictional but we should somehow streamline it with the naming of KVault, imho.

- KognitoIDP
- CognitoKMM

**Comment by gaebel** [comment]
I'm tending to Cognito-IdP or Kognito-IdP. Also in lowercase and/or without hyphen.

I think it is enough for SEO if we put KMM into the repo description and README. Additionally the lib will be placed in public KMM indexes (as mentioned in the KVault issue).

I'm not a big fan of the "k" thing. If we continue with this pattern all future libs need to have this. In some cases this is probably not a good fit.

**Comment by benjohnde** [comment]
@Ingwersaft @gaebel as Jan is heavily putting effort in #32 I would say we should come to a decision. I am not against using the K as it somehow implies for which platform the library is usable. However we do not need to follow a consistent approach across all current and upcoming projects. Hence KVault could remain as is and we rename this project to `Cognito-IdP`. As Jan has a stronger opinion on the `we shall not use Kognito-IdP` side as I have, it is up to you to make the final call :)

**Comment by gaebel** [comment]
We could also omit the hyphen 🤔

**Comment by benjohnde** [comment]
- cognito-idp
- kognito-idp
- Cognito-idp
- Kognito-idp
- Cognito-Idp
- Kognito-Idp
- Cognito-IdP
- Kognito-IdP

Which one to pick @Ingwersaft? Which one do you prefer @gaebel? I would go with `kognito-idp`.

**Comment by Ingwersaft** [comment]
Personally `cognito-idp` hands down :D

I have a strong opinion against littering kotlin project names with `K`s all over the place....

**Comment by benjohnde** [comment]
Then, if @gaebel does not disagree: we go with `cognito-idp`! :)
