### ISSUE TITLE
Unable to verify secret hash for client, when testing locally

### ISSUE THREAD

**Issue by Nikola-Milovic** [Liftric/cognito-idp#34]
I'd prefer if this was a discussion rather than an issue but here it goes. Tried to use my own User Pool and my own AppClientID, which results in 9/23 test cases failing for the same reason `NotAuthorizedException: Unable to verify secret hash for client qe19*****************53>`. Did I misunderstand something?

As I am not using Vault by Hashicorp, I have no workaround as of yet for the generated env file so instead I am hardcoding the values in the test configuration 

```
expect class AuthHandlerIntegrationTests : AbstractAuthHandlerIntegrationTests

abstract class AbstractAuthHandlerIntegrationTests {
    private val configuration = Configuration(
        Region.euCentral1,
        "qe19****************53"
    )
```

Running with `./gradlew test`

**Comment by benjohnde** [comment]
It's basically because of this one here https://stackoverflow.com/a/41451596. Most of the api doesn't handle the client secret properly. I highly believe that's the reason while nearly all the Cognito client's for various platforms haven't emphasise that attribute.
