### ISSUE TITLE
Forgot Password request does not return failure with unknown username

### ISSUE THREAD

**Issue by burnhamd** [Liftric/cognito-idp#35]
When making a forgot password request with a user phone number that does not exist in the cognito pool, I get a success on the request.

From the documentation at https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ForgotPassword.html

I was expecting a invalid parameter exception.  Is this an issue with cognito or library?

**Comment by gaebel** [comment]
Hi :) This should be intentional by Cognito and is also in line with the OWASP standard. Looks like it can be [configured](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-managing-errors.html).
