### ISSUE TITLE
iOS integration tests

### ISSUE THREAD

**Issue by gaebel** [Liftric/cognito-idp#6]
Think about temporary solution for iOS testing as long as the test target (klib) is not able to execute ktor on main thread: you are either stuck in mutation exception due to frozen thread or endless blocking.

**Comment by gaebel** [comment]
Meanwhile it's possible. The URLSession SSL trust verification doesn't work, though.

**Comment by gaebel** [comment]
I'm not sure if this needs to get tested under iOS. The integration tests are only there to test if the requests succeed, if this works in Android it should also work in iOS. One case would be to catch mutation exceptions (happened twice), this can be avoided with manually building before push though. What do you think @benjohnde?

**Comment by Ingwersaft** [comment]
If this already happened twice, some automated tests are definitely in order, if possible :)
