### ISSUE TITLE
Does not seem to work anymore

### ISSUE THREAD

**Issue by Burf2k** [Liftric/cognito-idp#62]
So I am trying to use this on a Kotlin multiplatform project

I have 
```
val provider = IdentityProviderClient("eu-west-2", "CLIENT ID FROM AWS")

suspend fun login() {
        provider.signUp("2yoqr44v", "Headache1!").fold(
            onSuccess = {
                // Do something
                print("login")
            },
            onFailure = {
                // Handle exceptions
                print(it.message)
            }
        )
    }
```

I get back
Unable to resolve host "cognito-idp.eu-west-2.amazonaws.com": No address associated with hostname

**Comment by benjohnde** [comment]
Hm good, have you tried to open or curl `cognito-idp.eu-west-2.amazonaws.com`? I guess the problem has something to do with name resolving. We don't have any issues at all. Could you further dive into that issue, e.g. with the debugger and pipe more information through?

**Comment by dpmaddy** [comment]
@benjohnde I've just run into a similar problem, I'll try document my findings below...

To start, I'm using Amplify for my backend. By default Amplify sets up their authentication to use the `AuthFlow: "USER_SRP_AUTH"`, which means an additional `SRP_A` parameter is required in the `signIn` flow [ref](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-authentication-flow.html).

I wonder if this is whats causing the problem, I duplicated the request sent by `cognito-idp` and your using `USER_PASSWORD_AUTH`, see below for req + res.

**Request**
```bash
curl --location 'https://cognito-idp.<your-region>.amazonaws.com/' \
--header 'Content-Type: application/x-amz-json-1.1' \
--header 'X-Amz-Target: AWSCognitoIdentityProviderService.InitiateAuth' \
--data '{
    "AuthParameters": {
        "USERNAME": "user.name",
        "PASSWORD": "PotentialCause"
    },
    "AuthFlow": "USER_PASSWORD_AUTH",
    "ClientId": "CLIENT_ID"
}'
```

**Response**
```json
{
    "__type": "InvalidParameterException",
    "message": "USER_PASSWORD_AUTH flow not enabled for this client"
}
```

For now to solve this problem, I've created an additional app client for Cognito (AWS > Cognito > User Pool > App Integration > Create app client > ALLOW_USER_PASSWORD_AUTH) however this is not something I'd do for a production environment. 
After updating my ClientId `var provider = IdentityProviderClient("REGION", "NEW CLIENT ID")` in the app, everything worked as expected :)

It seems like this might relate to [#61](https://github.com/Liftric/cognito-idp/issues/61), how difficult would you estimate it to be to add these additional flows??
For the SRP flow, I found a comment showing how this was done for the Kotlin / JS libs [here](https://stackoverflow.com/a/41155990/21338228)
