### ISSUE TITLE
Calling a Lambda function

### ISSUE THREAD

**Issue by burf2000** [Liftric/cognito-idp#66]
Thank you for making this epic framework

Do you have any idea how to then call a Lambda function from it?  Sorry I know its a bit off topic but I cant seem to work out how to call one (Have the functions etc, work in AWS)

**Comment by vbudilov** [comment]
What needs to invoke a Lambda function? If you're trying to invoke it from the UI then you need to deploy a function and front it with ALB or API Gateway. If you want the Lambda function to be invoked by Cognito then you can setup hooks. More details needed here.

**Comment by benjohnde** [comment]
Sry have to close it, @vbudilov is right and it probably is more related to general AWS setup.
