### ISSUE TITLE
Can I delete user by email?

### ISSUE THREAD

**Issue by a-blekot** [Liftric/cognito-idp#67]
Hello)
I have the next flow in my application

1) SignUp (email, password, password confirmation) -> `provider.signUp(email, password)`

2) Confirm Email -> `provider.confirmSignUp(email, code)`

The problem is that the user can't navigate back to 1st screen and change the password for example.

if he will try to SignUp again with the same email he receives `IdentityProviderException.Unknown("... email already exists")`

And I can't delete the user from Cognito because the delete method requires accessToken `provider.deleteUser(accessToken)`

Please suggest what should I do

**Comment by benjohnde** [comment]
Sry for the late answer: @a-blekot not quite sure whether I understood your first issue, cannot relate. The functions work as intended and I won't give support to your individual app flow. Confirming SignUp, Resending Confirmation Code as well as Password Change works. Cognito disallows re-signup with the same email address once it is confirmed, which is a desired behaviour.

The accessToken is necessary for deleteUser, that is true. You can see a sample usage in the following test: https://github.com/Liftric/cognito-idp/blob/master/src/commonTest/kotlin/com/liftric/cognito/idp/IdentityProviderClientTests.kt#L66

Hope that helps, cheers!

**Comment by a-blekot** [comment]
@benjohnde Thank you for reply)

 should I also pass attributes to `signUp` method?

``` kotlin
val signUpResponse = provider.signUp(
    credentials.username, credentials.password,
    attributes = listOf(
        UserAttribute(Name = "custom:target_group", Value = "ROLE_USER")
    )
)
```

**Comment by benjohnde** [comment]
@a-blekot https://github.com/Liftric/cognito-idp?tab=readme-ov-file#sign-up
> Attributes are optional.
