### ISSUE TITLE
Any suggestions on where to store the tokens once they're retrieved? 

### ISSUE THREAD

**Issue by vbudilov** [Liftric/cognito-idp#68]
Thanks for the framework! 

Do you have any suggestions, or are you planning on adding a feature, where the tokens are stored locally (in a datastore or something similar) and implementing a CognitoService class that returns the JWT tokens or, if they're expired, requesting and returning refreshed ones? 

Thanks!

**Comment by benjohnde** [comment]
@vbudilov we thought about that, but every app got individual requirements for a `Session` and more importantly where it should reside. We have created an individual `validateAccessToken` method which checks for expiry and also performs an automatic refresh.
